<?php

return [
    // rules
    'differs' => \peel\validate\rules\Differs::class . '>isValid',
    'matches' => \peel\validate\rules\Matches::class . '>isValid',
    'allowempty' => \peel\validate\rules\allowEmpty::class . '>isValid',
    'alpha' => \peel\validate\rules\alpha::class . '>isValid',
    'alphadash' => \peel\validate\rules\alphaDash::class . '>isValid',
    'alphanumeric' => \peel\validate\rules\alphaNumeric::class . '>isValid',
    'alphanumericdash' => \peel\validate\rules\alphaNumericDash::class . '>isValid',
    'alphanumericspace' => \peel\validate\rules\alphaNumericSpace::class . '>isValid',
    'alphaspace' => \peel\validate\rules\alphaSpace::class . '>isValid',
    'exactlength' => \peel\validate\rules\exactLength::class . '>isValid',
    'greaterthan' => \peel\validate\rules\greaterThan::class . '>isValid',
    'greaterthanequalto' => \peel\validate\rules\greaterThanEqualTo::class . '>isValid',
    'human' => \peel\validate\rules\human::class . '>isValid',
    'isarray' => \peel\validate\rules\isArray::class . '>isValid',
    'isbool' => \peel\validate\rules\isBool::class . '>isValid',
    'isclass' => \peel\validate\rules\isClass::class . '>isValid',
    'isdecimal' => \peel\validate\rules\isDecimal::class . '>isValid',
    'isfloat' => \peel\validate\rules\isFloat::class . '>isValid',
    'ishex' => \peel\validate\rules\isHex::class . '>isValid',
    'isinteger' => \peel\validate\rules\isInteger::class . '>isValid',
    'islowercase' => \peel\validate\rules\isLowercase::class . '>isValid',
    'isnatural' => \peel\validate\rules\isNatural::class . '>isValid',
    'isnaturalnozero' => \peel\validate\rules\isNaturalNoZero::class . '>isValid',
    'isnumeric' => \peel\validate\rules\isNumeric::class . '>isValid',
    'isscalar' => \peel\validate\rules\isScalar::class . '>isValid',
    'isstdclass' => \peel\validate\rules\isStdClass::class . '>isValid',
    'isstring' => \peel\validate\rules\isString::class . '>isValid',
    'isuppercase' => \peel\validate\rules\isUppercase::class . '>isValid',
    'lessthan' => \peel\validate\rules\lessThan::class . '>isValid',
    'lessthanequalto' => \peel\validate\rules\lessThanEqualTo::class . '>isValid',
    'maxlength' => \peel\validate\rules\maxLength::class . '>isValid',
    'minlength' => \peel\validate\rules\minLength::class . '>isValid',
    'oneof' => \peel\validate\rules\oneOf::class . '>isValid',
    'regexmatch' => \peel\validate\rules\regexMatch::class . '>isValid',
    'required' => \peel\validate\rules\required::class . '>isValid',
    'validbase64' => \peel\validate\rules\validBase64::class . '>isValid',
    'validdate' => \peel\validate\rules\validDate::class . '>isValid',
    'validemail' => \peel\validate\rules\validEmail::class . '>isValid',
    'validemails' => \peel\validate\rules\validEmails::class . '>isValid',
    'validip' => \peel\validate\rules\validIP::class . '>isValid',
    'validjson' => \peel\validate\rules\validJson::class . '>isValid',
    'validtimezone' => \peel\validate\rules\validTimezone::class . '>isValid',
    'validurl' => \peel\validate\rules\validURL::class . '>isValid',
    'validuuid' => \peel\validate\rules\validUuid::class . '>isValid',

    // filters
    'convertdate' => \peel\validate\filters\ConvertDate::class . '>filter',
    'filename' => \peel\validate\filters\Filename::class . '>filter',
    'human' => \peel\validate\filters\Human::class . '>filter',
    'input' => \peel\validate\filters\Input::class . '>filter',
    'integer' => \peel\validate\filters\Integer::class . '>filter',
    'length' => \peel\validate\filters\Length::class . '>filter',
    'map' => \peel\validate\filters\Map::class . '>filter',
    'number' => \peel\validate\filters\Number::class . '>filter',
    'slug' => \peel\validate\filters\Slug::class . '>filter',
    'str' => \peel\validate\filters\Str::class . '>filter',
    'strtolower' => \peel\validate\filters\StrToLower::class . '>filter',
    'strtoupper' => \peel\validate\filters\StrToUpper::class . '>filter',
    'textarea' => \peel\validate\filters\Textarea::class . '>filter',
    'trim' => \peel\validate\filters\Trim::class . '>filter',
    'visible' => \peel\validate\filters\Visible::class . '>filter',
];
